import { DosageType } from "./DosageType";

export default [
  {
    id: 1,
    name: "Omeprazole 20mg Capsule",
    description:
      "Treatment of stomach and intestinal ulcers, GERD/ gastro-esophageal reflux disease, erosive esophagitis, heartburn (acid regurgitation from stomach up to the mouth), and Zollinger-Ellison Syndrome.",
    dosage: 20,
    dosageType: DosageType.mg,
    price: 16.00,
    imageUrl: "omeprazole-20mg",
    isGeneric: true,
    brandName: "Omeprazole Capsule",
    isPrescriptionRequired: true,
    category: ["Antiulcerants", "Proton Pump Inhibitors"],
    manufacturer: "PhilCure",
  },
  {
    id: 2,
    name: "Omeprazole 40mg Capsule",
    description:
      "Treatment of stomach and intestinal ulcers, GERD/ gastro-esophageal reflux disease, erosive esophagitis, heartburn (acid regurgitation from stomach up to the mouth), and Zollinger-Ellison Syndrome.",
    dosage: 40,
    dosageType: DosageType.mg,
    price: 25.00,
    imageUrl: "omeprazole-40mg",
    isGeneric: false,
    brandName: "Omeprazole Capsule",
    isPrescriptionRequired: true,
    category: ["Antiulcerants", "Proton Pump Inhibitors"],
    manufacturer: "PhilCure",
  },
  {
    id: 3,
    name: "Trimetazidine 30mg Capsule",
    description: "Treatment and prevention of angina attacks (chest pain). Long-term treatment of coronary insufficiency (inadequate blood flow through one or more coronary arteries).",
    dosage: 30,
    dosageType: DosageType.mg,
    price: 10.00,
    imageUrl: "trimetazidine-30mg",
    isGeneric: true,
    brandName: "Trimetazidine Capsule",
    isPrescriptionRequired: true,
    category: ["Anti-anginal Drugs", "Chest pain"],
    manufacturer: "PhilCure",
  },
  {
    id: 4,
    name: "Amlodipine Besilate 5mg Tablet",
    description: "Used in the management of high blood pressure, coronary artery disease (CAD), angina (chest pain), and myocardial ischemia.",
    dosage: 5,
    dosageType: DosageType.mg,
    price: 4.00,
    imageUrl: "amlodipine-besilate-5mg",
    isGeneric: false,
    brandName: "Amlodipine Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "Calcium Channel Blockers"],
    manufacturer: "PhilCure",
  },
  {
    id: 5,
    name: "Amlodipine Besilate 10mg Tablet",
    description: "Used in the management of high blood pressure, coronary artery disease (CAD), angina (chest pain), and myocardial ischemia.",
    dosage: 5,
    dosageType: DosageType.mg,
    price: 8.00,
    imageUrl: "amlodipine-besilate-10mg",
    isGeneric: false,
    brandName: "Amlodipine Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "Calcium Channel Blockers"],
    manufacturer: "PhilCure",
  },
  {
    id: 6,
    name: "Losartan 50mg Tablet",
    description: "Used in the management of high blood pressure, heart failure, and myocardial infarction or heart attack. Available as film-coated tablet.",
    dosage: 50,
    dosageType: DosageType.mg,
    price: 10.00,
    imageUrl: "losartan-potassium",
    isGeneric: false,
    brandName: "Losartan Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "ARB"],
    manufacturer: "PhilCure",
  },
  {
    id: 7,
    name: "Rosuvastatin 10mg Tablet",
    description: "Used to lower cholesterol levels in the blood. For the prevention of stroke and heart attack in high-risk patients.",
    dosage: 10,
    dosageType: DosageType.mg,
    price: 18.00,
    imageUrl: "rosuvastatin-10mg",
    isGeneric: false,
    brandName: "Rosuvastatin Tablet",
    isPrescriptionRequired: true,
    category: ["Lipid Regulating Agents", "Cholesterol"],
    manufacturer: "PhilCure",
  },

  {
    id: 8,
    name: "Rosuvastatin 20mg Tablet",
    description: "Used to lower cholesterol levels in the blood. For the prevention of stroke and heart attack in high-risk patients.",
    dosage: 20,
    dosageType: DosageType.mg,
    price: 22.00,
    imageUrl: "rosuvastatin-20mg",
    isGeneric: false,
    brandName: "Rosuvastatin Tablet",
    isPrescriptionRequired: true,
    category: ["Lipid Regulating Agents", "Cholesterol"],
    manufacturer: "PhilCure",
  },

  {
    id: 9,
    name: "Metformin HCI 500mg Tablet",
    description: "Used alone or in combination with other antidiabetic drug to treat patients with type 2 diabetes (NIDDM or non-insulin dependent diabetes mellitus) when diet and exercise alone failed to control blood sugar levels.",
    dosage: 500,
    dosageType: DosageType.mg,
    price: 3.00,
    imageUrl: "metformin-hci",
    isGeneric: false,
    brandName: "Metformin Tablet",
    isPrescriptionRequired: true,
    category: ["Antidiabetic", "Biguanides"],
    manufacturer: "PhilCure",
  },

  {
    id: 10,
    name: "Telmisartan 40mg Tablet",
    description: "Used in the treatment of high blood pressure and prevention of stroke, heart attack, and death in high risk patients.",
    dosage: 40,
    dosageType: DosageType.mg,
    price: 10.00,
    imageUrl: "telmisartan-40mg",
    brandName: "Telmisartan Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "ARB"],
    manufacturer: "PhilCure",
  },

  {
    id: 11,
    name: "Telmisartan +hydrochlorothiazide 40mg Tablet",
    description: "Used in the treatment of high blood pressure and prevention of stroke, heart attack, and death in high risk patients.",
    dosage: 40,
    dosageType: DosageType.mg,
    price: 13.00,
    imageUrl: "telmisartan+h-40mg",
    brandName: "Telmisartan+h Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "ARB"],
    manufacturer: "PhilCure",
  },

  {
    id: 12,
    name: "Telmisartan +hydrochlorothiazide 40mg Tablet",
    description: "Used in the treatment of high blood pressure and prevention of stroke, heart attack, and death in high risk patients.",
    dosage: 40,
    dosageType: DosageType.mg,
    price: 13.00,
    imageUrl: "telmisartan+h-40mg",
    brandName: "Telmisartan+h Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "ARB"],
    manufacturer: "PhilCure",
  },

  {
    id: 13,
    name: "Carvedilol 25mg Tablet",
    description: "Management of high blood pressure, angina (chest pain), and heart failure.",
    dosage: 25,
    dosageType: DosageType.mg,
    price: 6.00,
    imageUrl: "carvedilol-25mg",
    brandName: "Carvedilol Tablet",
    isPrescriptionRequired: true,
    category: ["Antihypertensive", "Beta-blockers"],
    manufacturer: "PhilCure",
  },

  {
    id: 14,
    name: "Clopidogrel 75mg Tablet",
    description: "Prevention of stroke, heart attack, and cardiovascular incidences or death in high risk patients. Available as film-coated tablet.",
    dosage: 75,
    dosageType: DosageType.mg,
    price: 12.00,
    imageUrl: "clodipogrel-75mg",
    brandName: "Clopidogrel Tablet",
    isPrescriptionRequired: true,
    category: ["Antithrombotic", "Stroke"],
    manufacturer: "PhilCure",
  },

  
];
