export default [
  {
    id: 1,
    name: "Product 1",
    description: "This is a product description",
    dosage: 250,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 1",
    isPrescriptionRequired: false,
    category: ["Category 1", "Category 2"],
  },
  {
    id: 2,
    name: "Product 2",
    description: "This is a product description",
    dosage: 100,
    price: 50,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 2",
    isPrescriptionRequired: false,
    category: ["Category 3", "Category 1"],
  },
  {
    id: 3,
    name: "Product 3",
    description: "This is a product description",
    dosage: 504,
    price: 200,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: true,
    brandName: "Brand 3",
    isPrescriptionRequired: true,
    category: ["Category 2", "Category 3"],
  },
  {
    id: 4,
    name: "Product 4",
    description: "This is a product description",
    dosage: 250,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 4",
    isPrescriptionRequired: false,
    category: ["Category 1", "Category 2"],
  },
  {
    id: 5,
    name: "Product 5",
    description: "This is a product description",
    dosage: 10,
    price: 5,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: true,
    brandName: "Brand 5",
    isPrescriptionRequired: false,
    category: ["Category 3", "Category 1"],
  },
  {
    id: 6,
    name: "Product 6",
    description: "This is a product description",
    dosage: 250,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 6",
    isPrescriptionRequired: false,
    category: ["Category 2", "Category 3"],
  },
  {
    id: 7,
    name: "Product 7",
    description: "This is a product description",
    dosage: 500,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 6",
    isPrescriptionRequired: true,
    category: ["Category 1", "Category 2"],
  },
];
