import { DosageType } from "./DosageType";

export default [
  {
    id: 1,
    name: "Paracetamol",
    description:
      "Paracetamol (Biogesic) is a medication that is typically used to relieve mild to moderate pain such as headache, backache, menstrual cramps, muscular strain, minor arthritis pain, toothache, and reduce fevers caused by illnesses such as the common cold and flu.",
    dosage: 500,
    dosageType: DosageType.mg,
    price: 4.81,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Biogesic",
    isPrescriptionRequired: false,
    category: ["Headache", "Fever"],
    manufacturer: "Unilab",
  },
  {
    id: 2,
    name: "Product 2",
    description: "This is a product description",
    dosage: 100,
    dosageType: DosageType.ml,
    price: 50,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 2",
    isPrescriptionRequired: false,
    category: ["Category 3", "Category 1"],
    manufacturer: "Manufacturer 2",
  },
  {
    id: 3,
    name: "Product 3",
    description: "This is a product description",
    dosage: 504,
    dosageType: DosageType.mg,
    price: 200,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: true,
    brandName: "Brand 3",
    isPrescriptionRequired: true,
    category: ["Category 2", "Category 3"],
    manufacturer: "Manufacturer 3",
  },
  {
    id: 4,
    name: "Product 4",
    description: "This is a product description",
    dosage: 250,
    dosageType: DosageType.mg,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 4",
    isPrescriptionRequired: false,
    category: ["Category 1", "Category 2"],
    manufacturer: "Manufacturer 1",
  },
  {
    id: 5,
    name: "Product 5",
    description: "This is a product description",
    dosage: 10,
    dosageType: DosageType.ml,
    price: 5,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: true,
    brandName: "Brand 5",
    isPrescriptionRequired: false,
    category: ["Category 3", "Category 1"],
    manufacturer: "Manufacturer 2",
  },
  {
    id: 6,
    name: "Product 6",
    description: "This is a product description",
    dosage: 250,
    dosageType: DosageType.mg,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 6",
    isPrescriptionRequired: false,
    category: ["Category 2", "Category 3"],
    manufacturer: "Manufacturer 3",
  },
  {
    id: 7,
    name: "Product 7",
    description: "This is a product description",
    dosage: 500,
    dosageType: DosageType.mg,
    price: 100,
    imageUrl: "https://via.placeholder.com/150",
    isGeneric: false,
    brandName: "Brand 6",
    isPrescriptionRequired: true,
    category: ["Category 1", "Category 2"],
    manufacturer: "Manufacturer 1",
  },
];
